PhoneStore.WebUI/Controllers/CartController.cs
using PhoneStore.Domain.Abstract;
using PhoneStore.Domain.Entities;
using PhoneStore.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace PhoneStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IPhoneRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IPhoneRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int phoneId, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(g => g.PhoneId == phoneId);

            if (phone != null)
            {
                cart.AddItem(phone, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int phoneId, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(g => g.PhoneId == phoneId);

            if (phone != null)
            {
                cart.RemoveLine(phone);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


    }
}

PhoneStore.WebUI/Controllers/NavController.cs
using PhoneStore.Domain.Abstract;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PhoneStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IPhoneRepository repository;
        public NavController(IPhoneRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Phones
                .Select(phone => phone.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView("FlexMenu", categories);
        }

    }
}

PhoneStore.WebUI/Controllers/PhoneController.cs
using PhoneStore.Domain.Abstract;
using PhoneStore.Domain.Entities;
using PhoneStore.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace PhoneStore.WebUI.Controllers
{
    public class PhoneController : Controller
    {
        private IPhoneRepository repository;
        public int pageSize = 4;
        public PhoneController(IPhoneRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(string category, int page = 1)
        {
            PhonesListViewModel model = new PhonesListViewModel
            {
                Phones = repository.Phones
                .Where(p => category == null || p.Category == category)
                .OrderBy(phone => phone.PhoneId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Phones.Count() :
                    repository.Phones.Where(phone => phone.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int phoneId)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == phoneId);
            if (phone != null)
            {
                return File(phone.ImageData, phone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

PhoneStore.WebUI/Views/Shared/PhoneSummary.Mobile.cshtml
@model PhoneStore.Domain.Entities.Phone

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("# грн"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.PhoneId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

PhoneStore.WebUI/Views/Shared/PhoneSummary.cshtml
@model PhoneStore.Domain.Entities.Phone

    <div class="well">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Phone",
                         new { Model.PhoneId})" />
            </div>
        }
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("# грн")</span>
        </h3>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.PhoneId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Добавить в корзину" />
            </div>
        }
        <span class="lead">@Model.Description</span>
    </div>

PhoneStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

PhoneStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="https://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>PhoneStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

PhoneStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
        .navbar-brand {
           margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">PhoneStore - магазин мобильных телефонов</span>
            <div class="visible-xs">Phone</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>

    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>

    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>