PhoneStore.WebUI/Controllers/AdminController.cs
using PhoneStore.Domain.Abstract;
using PhoneStore.Domain.Entities;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhoneStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IPhoneRepository repository;
        public AdminController(IPhoneRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Phones);
        }

        public ViewResult Edit(int phoneId)
        {
            Phone phone = repository.Phones.FirstOrDefault(p => p.PhoneId == phoneId);
            return View(phone);
        }
        [HttpPost]
        public ActionResult Edit(Phone phone, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    phone.ImageMimeType = image.ContentType;
                    phone.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(phone.ImageData, 0, image.ContentLength);
                }
                repository.SavePhone(phone);
                TempData["message"] = string.Format("Изменения в телефоне \"{0}\" были сохранены", phone.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(phone);
            }
        }
        public ViewResult Create()
        {
            return View("Edit", new Phone());
        }
        [HttpPost]
        public ActionResult Delete(int phoneId)
        {
            Phone deletedPhone = repository.DeletePhone(phoneId);
            if (deletedPhone != null)
            {
                TempData["message"] = string.Format("Телефон \"{0}\" был удален",
                    deletedPhone.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

PhoneStore.WebUI/Controllers/PhoneController.cs
using PhoneStore.Domain.Abstract;
using PhoneStore.Domain.Entities;
using PhoneStore.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace PhoneStore.WebUI.Controllers
{
    public class PhoneController : Controller
    {
        private IPhoneRepository repository;
        public int pageSize = 4;
        public PhoneController(IPhoneRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(string category, int page = 1)
        {
            PhonesListViewModel model = new PhonesListViewModel
            {
                Phones = repository.Phones
                .Where(p => category == null || p.Category == category)
                .OrderBy(phone => phone.PhoneId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Phones.Count() :
                    repository.Phones.Where(phone => phone.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int phoneId)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == phoneId);
            if (phone != null)
            {
                return File(phone.ImageData, phone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

PhoneStore.WebUI/Views/Admin/Edit.cshtml
@model PhoneStore.Domain.Entities.Phone

@{
    ViewBag.Title = "Админ панель: редактирование товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование телефона «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.PhoneId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "PhoneId":
                    case "ImageData":
                    case "ImageMimeType":
                        //do nothing
                        break;
                    default:
                        <div class="form-group">
                            <label>
                                @(property.DisplayName ?? property.PropertyName)
                            </label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
            new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextArea(property.PropertyName, null,
            new { @class = "form-control" })

                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }

            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Phone",
                        new { Model.PhoneId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

PhoneStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<PhoneStore.Domain.Entities.Phone>

@{
    ViewBag.Title = "Админ панель: список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Список телефонов</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th class="text-right">ID</th>
                    <th>Название</th>
                    <th class="text-right">Цена</th>
                    <th class="text-center">Действия</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-right">@item.PhoneId</td>
                        <td>@Html.ActionLink(item.Name, "Edit", new { item.PhoneId })</td>
                        <td class="text-right">@item.Price.ToString("# грн")</td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("PhoneId", item.PhoneId)
                                <input type="submit"
                                       class="btn btn-default btn-xs"
                                       value="Удалить" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Добавить телефон", "Create", null,
                new { @class = "btn btn-default" })
        </div>
    </div>